openapi: "3.0.1"
info:
  version: 0.0.1
  title: Test Push Server API
  description: Test Push Server API
paths:
  /topic:
    post:
      operationId: postHook
      responses:
        default:
          description: "Default response for POST /topic"
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/hook'

components:
  x-amazon-apigateway-integrations:
    hook:
      type: AWS_PROXY
      httpMethod: GET
      uri: "${example_function_arn}"
      payloadFormatVersion: "2.0"
      connectionType: INTERNET
