openapi: "3.0.1"
info:
  version: 0.0.1
  title: Data Lake API
  description: Data Lake API
paths:
  /{projectId}:
    get:
      operationId: getStats
      responses:
        default:
          description: "Default response for GET /{projectId}"
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/stats'

components:
  x-amazon-apigateway-integrations:
    stats:
      type: AWS_PROXY
      httpMethod: GET
      uri: "${example_function_arn}"
      payloadFormatVersion: "2.0"
      connectionType: INTERNET
