name: ci

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'terraform/**'
      - 'docs/**'
      - 'README.md'

  push:
    branches: ['master', 'feat/ci']
    paths-ignore:
      #- '.github/**'
      - 'terraform/**'
      - 'docs/**'
      - 'README.md'

  workflow_dispatch:
    inputs:

concurrency:
  # Support push/pr as event types with different behaviors each:
  # 1. push: queue up builds
  # 2. pr: only allow one run per PR
  group: ${{ github.workflow }}-${{ github.event_name }}${{ github.event.pull_request.number }}
  # If there is already a workflow running for the same pull request, cancel it
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  tasks:
    name: "${{ matrix.cargo.name }}"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        cargo:
          - name: "Clippy"
            cmd: clippy
            args: --all-features --tests -- -D warnings
            rust: stable
          - name: "Formatting"
            cmd: fmt
            args: -- --check
            rust: nightly
          - name: "Unit Tests"
            cmd: test
            args: --all-features
            rust: stable
          - name: "Build Lambda"
            cmd: lambda
            args: build --release --arm64 --output-format zip
            rust: stable
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Install Rust toolchain
      - name: "Install Rust ${{ matrix.cargo.rust }}"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.cargo.rust }}
          profile: default
          override: true

      - name: "Cargo ${{ matrix.cargo.name }}"
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.cargo.cmd }}
          args: ${{ matrix.cargo.args }}
